"""Course Mode bounded context."""

from .artifacts import (
    InvalidArtifactPathError,
    UnsupportedCourseStorageError,
    ensure_course_data_root,
    ensure_course_workspace,
    normalize_artifact_relative_path,
    open_course_artifact_for_read,
    write_course_artifact_atomic,
)
from .models import (
    ArtifactReference,
    Course,
    CourseJobStage,
    CourseJobStatus,
    CourseManifest,
    CourseProcessingJob,
    CourseSource,
    CourseStatus,
    ManifestEntry,
    ManifestRole,
    ManifestVisibility,
    Unit,
)
from .repository import (
    CourseImportResult,
    CourseInput,
    CoursePage,
    CourseRepository,
    InvalidJobRetryError,
    ManifestApprovalBlockedError,
    ManifestRevisionConflictError,
)
from .source_processing import (
    COURSE_MAX_FILE_BYTES,
    COURSE_MAX_TOTAL_BYTES,
    COURSE_SUPPORTED_EXTENSIONS,
    CourseIngestionAdapter,
    DefaultCourseIngestionAdapter,
    InvalidCourseSourceError,
)

__all__ = [
    "ArtifactReference",
    "Course",
    "CourseInput",
    "CourseImportResult",
    "CourseIngestionAdapter",
    "CoursePage",
    "CourseRepository",
    "CourseJobStage",
    "CourseJobStatus",
    "CourseManifest",
    "CourseProcessingJob",
    "CourseSource",
    "CourseStatus",
    "InvalidArtifactPathError",
    "InvalidCourseSourceError",
    "InvalidJobRetryError",
    "ManifestApprovalBlockedError",
    "ManifestEntry",
    "ManifestRevisionConflictError",
    "ManifestRole",
    "ManifestVisibility",
    "UnsupportedCourseStorageError",
    "Unit",
    "COURSE_MAX_FILE_BYTES",
    "COURSE_MAX_TOTAL_BYTES",
    "COURSE_SUPPORTED_EXTENSIONS",
    "DefaultCourseIngestionAdapter",
    "ensure_course_data_root",
    "ensure_course_workspace",
    "normalize_artifact_relative_path",
    "open_course_artifact_for_read",
    "write_course_artifact_atomic",
]
